<div id="footer" class="grid_12">
	<div id="footer-main">
		<div class="grid_3 alpha">
			<div id="footer-left">
				<a href="http://www.desales.edu"><img src="images/DeSaleslogoStacked.png" /></a>
			</div>
		</div>
		<div class="grid_9 omega">
			<div id="footer-right">
				<div id="last-update">
					<span class="small bold">Last Updated: <?php echo($last_updated); ?></span>&nbsp|&nbsp<a href="/deit">Technology Home</a> | <a href="http://www.desales.edu">Return to the DeSales Homepage</a>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="clear"></div>

<!-- DEIT's Google Analytics script for site tracking -->
<script type="text/javascript">
	var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
	document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
	try {
		var pageTracker = _gat._getTracker("UA-15284864-1");
		pageTracker._trackPageview();
	} 
	catch(err) {}
</script>
<!-- End DEIT's Google Analytics Code -->

<!-- DSU's web team's Analytics script for site tracking -->
<script type="text/javascript">
	var _gaq = _gaq || [];
	_gaq.push(['_setAccount', 'UA-4305794-11']);
	_gaq.push(['_trackPageview']);

	(function() {
		var ga = document.createElement('script');
		ga.type = 'text/javascript';
		ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0];
		s.parentNode.insertBefore(ga, s);
	})();
</script>
<!-- End DSU's web team's Google Analytics Code -->
<script type="text/javascript"> Cufon.now(); </script>